### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Deimos161** [Jessy1237/DwarfCraft_premerge#3]
As requested here is the error I am getting

2013-09-09 19:35:06 [SEVERE] "Silently" catching entity tracking error.
2013-09-09 19:35:06 [SEVERE] net.minecraft.server.v1_6_R2.ReportedException: Adding entity to track
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:116)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:86)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.track(EntityTracker.java:23)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.WorldManager.a(WorldManager.java:18)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.a(World.java:957)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.WorldServer.a(WorldServer.java:786)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.addEntity(World.java:950)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.addEntity(World.java:895)
2013-09-09 19:35:06 [SEVERE]    at com.sharesc.caliog.npclib.NPCManager$WL.onChunkLoad(NPCManager.java:100)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:138)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:119)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getBlockAt(CraftWorld.java:83)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getBlockAt(CraftWorld.java:482)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.Location.getBlock(Location.java:82)
2013-09-09 19:35:06 [SEVERE]    at com.sharesc.caliog.npclib.NPCManager$WL.onChunkLoad(NPCManager.java:98)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:138)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:119)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:494)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.Location.getChunk(Location.java:73)
2013-09-09 19:35:06 [SEVERE]    at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(Unknown Source)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
2013-09-09 19:35:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
2013-09-09 19:35:06 [SEVERE] Caused by: java.lang.IllegalStateException: Entity is already tracked!
2013-09-09 19:35:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:96)
2013-09-09 19:35:06 [SEVERE]    ... 44 more

**Comment by Jessy1237** [comment]
what were you doing at the time of the error?

**Comment by Deimos161** [comment]
nothing. I could just be standing there and this happens.
When I looked two days ago my log was at 22million bytes. All filled with this error

**Comment by Deimos161** [comment]
Yeah, I just started up my server and it started with errors. Nothing saying it failed, But just that spam.

**Comment by Deimos161** [comment]
any updated on the error?

**Comment by Jessy1237** [comment]
No but it has something to do with towny because towny is fire'ing an error in combination with dwarfcraft.

**Comment by Deimos161** [comment]
Hmmm, so talk to towny guys?

**Comment by Jessy1237** [comment]
Yer i'd say see what they say as well.

**Comment by Jessy1237** [comment]
Yer its a problem with the NPCLib, i fixed it so it shouldn't happen anymore.
