### ISSUE TITLE
Error on everything

### ISSUE THREAD

**Issue by FyllyMan** [Jessy1237/DwarfCraft_premerge#7]
01:56:47 [SEVERE] Could not pass event EntityDeathEvent to DwarfCraft v1.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:327)
        at net.minecraft.server.v1_6_R2.EntityInsentient.dropDeathLoot(EntityInsentient.java:202)
        at net.minecraft.server.v1_6_R2.EntityLiving.die(EntityLiving.java:757)
        at net.minecraft.server.v1_6_R2.EntityLiving.damageEntity(EntityLiving.java:709)
        at net.minecraft.server.v1_6_R2.EntityMonster.damageEntity(EntityMonster.java:39)
        at net.minecraft.server.v1_6_R2.EntityZombie.damageEntity(EntityZombie.java:127)
        at net.minecraft.server.v1_6_R2.Entity.x(Entity.java:310)
        at net.minecraft.server.v1_6_R2.EntityLiving.x(EntityLiving.java:145)
        at net.minecraft.server.v1_6_R2.EntityInsentient.x(EntityInsentient.java:111)
        at net.minecraft.server.v1_6_R2.Entity.l_(Entity.java:230)
        at net.minecraft.server.v1_6_R2.EntityLiving.l_(EntityLiving.java:1242)
        at net.minecraft.server.v1_6_R2.EntityInsentient.l_(EntityInsentient.java:150)
        at net.minecraft.server.v1_6_R2.EntityMonster.l_(EntityMonster.java:24)
        at net.minecraft.server.v1_6_R2.EntityZombie.l_(EntityZombie.java:185)
        at net.minecraft.server.v1_6_R2.World.entityJoinedWorld(World.java:1354)
        at net.minecraft.server.v1_6_R2.World.playerJoinedWorld(World.java:1335)
        at net.minecraft.server.v1_6_R2.World.tickEntities(World.java:1223)
        at net.minecraft.server.v1_6_R2.WorldServer.tickEntities(WorldServer.java:480)
        at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:572)
        at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
        at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
        at com.Jessy1237.DwarfCraft.events.DCEntityListener.onEntityDeath(DCEntityListener.java:355)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 26 more

**Comment by Jessy1237** [comment]
Has your config fully generated because one of the values in your config is null.

**Comment by FyllyMan** [comment]
If it won't generate correctly how can I make sure it does? Deleted its
configs and tried again but got the same

**Comment by Jessy1237** [comment]
Well its just i can't replicate this bug, i tried killing a zombie and just letting it die by sunlight and i couldn't get this error. The line in the code which is giving the error is if you have allowed blacklisting of worlds on your server. In the dwarfcraft config what does it say for  blacklist worlds should say something like true or false.

**Comment by FyllyMan** [comment]
Okay I cannot even get it to generate any config files now, it's in plugins but on server start no folders or files are generated by the plugin.

**Comment by Jessy1237** [comment]
Ohh i realised the problem, you are trying to load a 1.6.4 version of DwarfCraft on a 1.6.2 server, i think.
