### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by birksebi** [Jessy1237/DwarfCraft_premerge#9]
So i've got this Error Message Spam after the last Bukkit Update, which crashes the server. I've got a similar error bevore the update but back then the server didn't crash.
The Error dissapears if i disable Dwarfcraft, so i think it' s a Problem in Dwarfcraft 

2013-11-08 16:55:47 [SEVERE] "Silently" catching entity tracking error.
2013-11-08 16:55:47 [SEVERE] net.minecraft.server.v1_6_R3.ReportedException: Adding entity to track
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.EntityTracker.addEntity(EntityTracker.java:118)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.EntityTracker.addEntity(EntityTracker.java:86)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.EntityTracker.track(EntityTracker.java:23)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.WorldManager.a(WorldManager.java:18)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.World.a(World.java:1025)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.WorldServer.a(WorldServer.java:797)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.World.addEntity(World.java:1018)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.World.addEntity(World.java:945)
2013-11-08 16:55:47 [SEVERE]    at com.sharesc.caliog.npclib.NPCManager$WL.onChunkLoad(NPCManager.java:100)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getChunkAt(CraftWorld.java:118)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:82)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:484)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.Location.getBlock(Location.java:82)
2013-11-08 16:55:47 [SEVERE]    at com.sharesc.caliog.npclib.NPCManager$WL.onChunkLoad(NPCManager.java:98)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getChunkAt(CraftWorld.java:118)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:82)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:484)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.Location.getBlock(Location.java:82)
2013-11-08 16:55:47 [SEVERE]    at net.pl3x.pl3xgates.gates.Gate.getSignBlock(Gate.java:203)
2013-11-08 16:55:47 [SEVERE]    at net.pl3x.pl3xgates.gates.GateFactory.addGate(GateFactory.java:153)
2013-11-08 16:55:47 [SEVERE]    at net.pl3x.pl3xgates.gates.GateFactory.loadGates(GateFactory.java:243)
2013-11-08 16:55:47 [SEVERE]    at net.pl3x.pl3xgates.Pl3xGates.onEnable(Pl3xGates.java:45)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:288)
2013-11-08 16:55:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:270)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.MinecraftServer.l(MinecraftServer.java:321)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.MinecraftServer.f(MinecraftServer.java:298)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.MinecraftServer.a(MinecraftServer.java:258)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.DedicatedServer.init(DedicatedServer.java:165)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:399)
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
2013-11-08 16:55:47 [SEVERE] Caused by: java.lang.IllegalStateException: Entity is already tracked!
2013-11-08 16:55:47 [SEVERE]    at net.minecraft.server.v1_6_R3.EntityTracker.addEntity(EntityTracker.java:98)
2013-11-08 16:55:47 [SEVERE]    ... 54 more

**Comment by Jessy1237** [comment]
Yer its a problem with the NPCLib, i fixed it so it shouldn't happen anymore.

**Comment by birksebi** [comment]
And when do you upload the fixed version?
